[tool.cannula.codegen]
scalars = [
    "cannula.scalars.date.Date",
    "cannula.scalars.date.Datetime",
    "cannula.scalars.date.Time",
    "cannula.scalars.util.JSON",
    "cannula.scalars.util.UUID",
]
dest="_generated.py"
