# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

executors:
  default:
    docker:
      - image: cimg/python:3.9.16
    working_directory: ~/repo

jobs:
  build:
    executor: default

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements-test.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: make setup

      - save_cache:
          paths:
            - ./.venv
          key: v1-dependencies-{{ checksum "requirements-test.txt" }}

      - run:
          name: run tests
          command: make test

      - store_artifacts:
          path: test-reports
          destination: test-reports

  deploy:
    executor: default

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements-test.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: make setup

      - save_cache:
          paths:
            - ./.venv
          key: v1-dependencies-{{ checksum "requirements-test.txt" }}

      - run: make publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
