version: "3"

services:
  openstack:
    image: cannula-openstack-example
    command: ["python", "mock_server.py"]
    container_name: mock-openstack-server
    ports:
      - "8080:8080"
    volumes:
      - ./:/app

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: cannula-openstack-example
    container_name: cannula-openstack-server
    volumes:
      - ./:/app
      - ../../:/external/lib/
    ports:
      - "8081:8081"
